debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.example.sampleboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    # open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

---

spring:
  config:
    activate:
      on-profile: testdb
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:board;mode=mysql
#  sql:
#    init:
#      mode: always
#  test.database.replace: none